apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-2048
spec:
    replicas:3
    selector:
        matchLabels:
            app: deployment-2048
    template:
        metadata:
            labels:
                app: deployment-2048
        spec:
            containers:
                - name: deployment-2048
                  image: ronitgandhi/deployment-2048:latest
                  ports:
                      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: svc-2048
spec:
    type: NodePort
    selector:
        app: deployment-2048
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30007
